export const SliderData = [
    {
      image:
        'https://blog.venuelook.com/wp-content/uploads/2015/08/how-to-decide-upon-a-grand-wedding.webp'
    },
    {
      image:
        'https://royalpepper.in/blog/wp-content/uploads/2021/05/Mandap-decorations-ideas-for-weddings.png'
    },
    {
      image:
        'https://eventsbyliz.com.ph/wp-content/uploads/2019/06/Royal-Birthday-Celebration-for-John-Loid.-YaesoCoolAt21-JohnLoidXXI-EventsByL.xx&oh=515ca23291dbde2c29a1a282ee59a248&oe=5D84E49A.jpeg'
    },
    {
      image:
        'https://i0.wp.com/tourgossips.com/wp-content/uploads/2020/11/Romantic-Candlelight-Dinner-At-Beach.jpg?fit=1748%2C1240&ssl=1'
    },
    {
      image:
        'https://i.ytimg.com/vi/h0CId0WegCs/maxresdefault.jpg'
    },
    {
      image:
        'https://i.pinimg.com/originals/37/77/06/37770681359f5dd6e1f076dc12ba7cd0.jpg'
    },
    {
      image:
        'https://g3fashion.com/blog/wp-content/uploads/2015/09/thumb-2.jpg'
    },
    {
      image:
        'https://i.ytimg.com/vi/qdX7XjkLHWs/maxresdefault.jpg'
    },
    {
      image:
        'https://i.ytimg.com/vi/slISLUf9bGc/maxresdefault.jpg'
    }
  ];